meldon_catalog:
    resource: "@MeldonCatalogBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

user_new:
    path:     /register
    defaults: { _controller: "MeldonCatalogBundle:User:new" }
    methods:  [GET, POST]
