security:
    encoders:
        Meldon\CatalogBundle\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: MeldonCatalogBundle:User
                property: username

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout: true