security:
    encoders:
        Meldon\CatalogBundle\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: MeldonCatalogBundle:User
                property: username

    firewalls:
        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~