category_index:
    path:     /
    defaults: { _controller: "MeldonCatalogBundle:categoryEntity:index" }
    methods:  GET

category_show:
    path:     /{id}/show
    defaults: { _controller: "MeldonCatalogBundle:categoryEntity:show" }
    methods:  GET

category_new:
    path:     /new
    defaults: { _controller: "MeldonCatalogBundle:categoryEntity:new" }
    methods:  [GET, POST]

category_edit:
    path:     /{id}/edit
    defaults: { _controller: "MeldonCatalogBundle:categoryEntity:edit" }
    methods:  [GET, POST]

category_delete:
    path:     /{id}/delete
    defaults: { _controller: "MeldonCatalogBundle:categoryEntity:delete" }
    methods:  DELETE
