item_index:
    path:     /
    defaults: { _controller: "MeldonCatalogBundle:itemEntity:index" }
    methods:  GET

item_show:
    path:     /{id}/show
    defaults: { _controller: "MeldonCatalogBundle:itemEntity:show" }
    methods:  GET

item_new:
    path:     /new
    defaults: { _controller: "MeldonCatalogBundle:itemEntity:new" }
    methods:  [GET, POST]

item_edit:
    path:     /{id}/edit
    defaults: { _controller: "MeldonCatalogBundle:itemEntity:edit" }
    methods:  [GET, POST]

item_delete:
    path:     /{id}/delete
    defaults: { _controller: "MeldonCatalogBundle:itemEntity:delete" }
    methods:  DELETE

item_table_by_category:
  path:     /{id}/all
  defaults: {_controller: "MeldonCatalogBundle:itemEntity:showallbycategory"}
  methods: GET