param_index:
    path:     /
    defaults: { _controller: "MeldonCatalogBundle:parameterEntity:index" }
    methods:  GET

param_show:
    path:     /{id}/show
    defaults: { _controller: "MeldonCatalogBundle:parameterEntity:show" }
    methods:  GET

param_new:
    path:     /new
    defaults: { _controller: "MeldonCatalogBundle:parameterEntity:new" }
    methods:  [GET, POST]

param_edit:
    path:     /{id}/edit
    defaults: { _controller: "MeldonCatalogBundle:parameterEntity:edit" }
    methods:  [GET, POST]

param_delete:
    path:     /{id}/delete
    defaults: { _controller: "MeldonCatalogBundle:parameterEntity:delete" }
    methods:  DELETE
