<?php

namespace Meldon\CatalogBundle\Repository;

/**
 * categoryEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoryEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
