<?php

namespace Meldon\CatalogBundle\Repository;

/**
 * imageEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imageEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
