<?php

namespace Meldon\CatalogBundle\Repository;

/**
 * itemEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class itemEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
