<?php

namespace Meldon\CatalogBundle\Repository;

/**
 * ParameterItemEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterItemEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
