<?php

namespace Meldon\CatalogBundle\Repository;

/**
 * parameterEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class parameterEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
